name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v2.3.3
    
    - name: Run tests
      run: deno test --allow-net --allow-env
      env:
        STRIPE_SECRET: xxx
        DISCORD_BOT_TOKEN: xxx
        DISCORD_CHANNEL_ID: xxx
